### ISSUE TITLE
Implement docker detach/reattach test

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest-docker#128]
Docker **supports** detach in `tty` mode using `ctrl+p ctrl+q`. We should test it somehow. The problem is, how to send the `ctrl+p ctrl+q` sequence. According to:
http://stackoverflow.com/questions/11295550/python-pexpect-sendcontrol-key-characters

it should be possible, I succeeded when using screen:

<pre>
from autotest.client.shared import aexpect
b=aexpect.ShellSession("TERM=xterm screen -x")
b.sendline('\x01c')
b.sendline('a')
b.sendline('\x01\x01')
b.sendline('b')
</pre>

attached to running screen, created new terminal, executed comand a (not found), than switched to previously used terminal and executed command b (not found).

Anyway when I tried the same with docker:

<pre>
from autotest.client.shared import aexpect
a=aexpect.ShellSession("TERM=xterm docker run -t -i fedora bash")
a.sendline('\x11\x12')
print a.read_nonblocking()
a.sendline("echo $HOSTNAME")
print a.read_nonblocking()
</pre>

it was still inside the container. I even tried `a=aexpect.ShellSession("TERM=xterm bash -c 'docker run -t -i fedora bash'")` to make sure there is bash underneath, without luck.

@cevich, @jzupka do you have any suggestions? (btw `ctrl+c` works fine, so we can add it to the --sig-proxy test)

**Comment by cevich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) (CI) Test docker console detach/attach](https://trello.com/c/sRVrEf3P/394-3-ci-test-docker-console-detach-attach)
