### ISSUE TITLE
Develop way of handling multiple docker versions (flags)

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest-docker#297]
Find a way to easily specify flags, which are named differently in various docker versions, eg.:

``` bash
docker rmi --stop
docker rmi --force
```

**Comment by cevich** [comment]
Moving to 0.8.2

**Comment by ldoktor** [comment]
Is this still valid? Last update was on 2016, let's close it.

**Comment by cevich** [comment]
Hehe, forgot we even had open issues.  Closing all of them...
