### ISSUE TITLE
Develop test which starts container with broken symlink

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest-docker#349]
https://bugzilla.redhat.com/show_bug.cgi?id=1109855

Implement tests which tries to start container with broken `/usr/share/rhel/secrets/rhel7.repo` symlink

**Comment by cevich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) (CI) Test broken secrets symlink](https://trello.com/c/HtCqlhGj/407-3-ci-test-broken-secrets-symlink)
