### ISSUE TITLE
Test container access to shm resources

### ISSUE THREAD

**Issue by ldoktor** [autotest/autotest-docker#414]
Develop a test, which uses `ipcmk` and `ipcrm` to check `shm` distinguish namespaces correctly. This test shouldn't really use the memory, only verify segments are visible and removable (which confirms selinux rights).

test objectives:
1. Start container
2. Create IPC (ipcmk -$type $size; returns shmid)
3. (Verify presence/nonpresence+size in given namespace) Check IPC (ipcs -$type $shmid)
4. (Verify access) Remove IPC (ipcrm -$type $key/$ipcid)

variants:
- independent container, other dependent and check presence
- --ipc host, create dependent container and check presence
- IPC created before dependant containers are created
- create, SIGSTOP container, spawn new dependent container, check presence
- create independent containers and check nonpresence
- one --ipc host, other independent and check nonpresence
- try --ipc container:non-started container
- try --ipc container:already-stopped container
- deep containers
- ...

variants:
- -M (shmem)
- -S (semaphore)
- -Q (queue)

This test should extend the existing https://github.com/autotest/autotest-docker/pull/401 which uses different approach. Together they should cover the https://github.com/autotest/autotest-docker/issues/371

**Comment by cevich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) (CI) Test container access to shm resources](https://trello.com/c/sRVrEf3P/394-5-ci-test-container-access-to-shm-resources)
