### ISSUE TITLE
Fix build case

### ISSUE THREAD

**Issue by luwensu** [autotest/autotest-docker#426]
build.ini part:
1.Provide a default value for busybox_url, dockerfile_path(https_file, git_file), thus the we can directly run all cases with filling the repo in default.ini. Otherwise, we need another script to rember and fill all the necessary parameters in various cases.
2.Imporve timeout to 1200, from my test, the pull a fedora image maybe need more than 15 minutes in my env (China's net).

build.py part: 
for case "bad" and  "bad_force_rm"
1.#docker load -i "empty_base_image" has been discard by docker now, could we provide a parameter to replace "FROM empty_base_image" part, like "fedora"?
2.Change the expected_msg in build.ini through 1, since what i get is "/bin/sh: this_shoud_fail: command not found" via FROM rhel7

**Comment by cevich** [comment]
This issue has been resolved in 6b1dd97b302e572d478ab705407d7bdc8f98941a
