### ISSUE TITLE
Fix build stdout not accurate

### ISSUE THREAD

**Issue by luwensu** [autotest/autotest-docker#463]
1.A typo issue first
class build(subtest.SubSubtestCaller):
should be like this
        def setup(self):
       # super(build, self).reset_build_context()
        super(build, self).setup
        self.reset_build_context()

2.Then about the class postprocessing(object):
sub case "local" as instance
    def regex_postprocess(self, build_def, command, parameter):
            output = build_def.dockercmd.stdout
will get the pull image info instead of the build

3."local" case need a postproc_cmd_csv to pass !rx_err

**Comment by cevich** [comment]
@luwensu Next time, please open separate issues, so I don't loose track.   Also, when entering code, it's best to put inside markdown, see example here: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown you can also put in a diff :smile: 

For #1, oops, you're right, my fault.  Thanks. Should be

```diff
diff --git a/subtests/docker_cli/build/build.py b/subtests/docker_cli/build/build.py
index ed97d82..c28319e 100644
--- a/subtests/docker_cli/build/build.py
+++ b/subtests/docker_cli/build/build.py
@@ -62,7 +62,7 @@ class build(subtest.SubSubtestCaller):
             shutil.copytree(src, dst)
 
     def setup(self):
-        super(build, self).reset_build_context()
+        super(build, self).setup()
         self.reset_build_context()
 
     def cleanup(self):
```

I will fix quickly.

For # 2, If I understand correctly, is this https://bugzilla.redhat.com/show_bug.cgi?id=1186483 ?

For # 3, nope it will inherit value from main subtest section ``[docker_cli/build]`` but maybe I should put comment about this?  Okay, I will make quick fix.

**Comment by luwensu** [comment]
Got it, sorry for the mess up format, i should learn more the Markdown format.....
Well, i'll continue run the case again and again with the latest docker to see what i can fix or update.
Thanks you help again!

**Comment by cevich** [comment]
No worries, I got your meaning.  No need to learn all markdown, just a few handy things, like code blocks, makes things easier to read.  Not a big deal though, thanks for finding the bugs!
