### ISSUE TITLE
commit subtest check_commit_default fail

### ISSUE THREAD

**Issue by luwensu** [autotest/autotest-docker#497]
commit: check_default_cmd failed to postprocess
DockerTestFail
Unable to start image with default command: * Command: 
                	            /usr/bin/docker -D run --rm
                	            d70f570ec27a582c7f19cb5c82a6280c1f37a688737e0b92e89fbed7fbf7c8fb
                	        Exit status: 0
                	        Duration: 3.93485093117
                	        
stderr:
 time="2015-04-22T18:21:16+08:00" level=debug msg="Corrupted prefix: []" 
 time="2015-04-22T18:21:16+08:00" level=debug msg="[hijack] End of stdout" 
 time="2015-04-22T18:21:18+08:00" level=debug msg="End of CmdRun(), Waiting for hijack to finish."

The reason why it fails is because
`not self.config['check_results_contain'] in results.stdout` expects a stdout, 
but `docker_data_prepare_cmd = /bin/bash -c "echo '%%s' > /var/i" ` 
shows nothing as the content redirect to this file

**Comment by luwensu** [comment]
IMO, One way to fix is pass `docker_data_prepare_cmd` in  `[docker_cli/commit]`
into the sub case part and let the command in `[docker_cli/commit/check_default_cmd]`
redirect to stdout, i'll sent a patch to fix this tomorrow.

**Comment by cevich** [comment]
I didn't write this test and haven't looked deeply at the code in a long while.  Normally I just re-write the test from scratch since sometimes that is faster than trying to read old/mouldy code.  Anyway, thanks for the research into this, I'm glad you figured it out.  Another idea might be to change the command to use ``tee`` instead of simple redirect.  e.g. ``"echo '%%s' | tee /var/i"````.  Whatever way you think is best or most efficient is fine by me.  Thanks again for looking into this.

**Comment by luwensu** [comment]
Thanks so much! It's more easier than my thought.I only did a quick fix to make the case pass first.
And i wonder how to update the document, since i found subtest.rst is in the list of .gitignore.
If it's okay to add it back, i'd like to push a patch to make up the document, not much, just delete one line about `check_results_contain`.

**Comment by cevich** [comment]
I see from #501 I think you figured it out.  ``subtest.rst`` is automatically generated by parsing the main subtest module docstring and doing some magic with the corresponding ``ini`` file.  Assuming you have ``python-docutils`` and ``python-sphinx`` installed, running ``make`` should build it for you.  I thought I wrote some docs about this....hmmm, guess not, better add that to the list.

**Comment by cevich** [comment]
Docs link: http://docker-autotest.readthedocs.org/en/latest/#docker-cli-commit-subtest

(will rebuild based on #501 changes to master shortly)
