### ISSUE TITLE
Improve conf.py's compability for Sphinx v1.3.1

### ISSUE THREAD

**Issue by luwensu** [autotest/autotest-docker#538]
If apply the current conf.py for Sphinx v1.3.1, it will trigger few errors:

`Warning, treated as error:
WARNING: the config value 'latex_show_urls' has type `bool', defaults to `str.'
`
`
Warning, treated as error:
WARNING: the config value 'html_short_title' has type `NoneType', defaults to `str.'
`
`Warning, treated as error:
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
`

**Comment by cevich** [comment]
Travis has Sphinx locked down to version v1.2.2 because that's what matches RHEL also.  If you're seeing this error in Fedora then I'd just not worry about it.  The unittests that matter are the ones that run in Travis with the older version.

**Comment by cevich** [comment]
closing this unless it becomes a problem for ``readthedocs.io`, then we can re-open.
