### ISSUE TITLE
Reimplement some dockertest/docker_daemon.py functions

### ISSUE THREAD

**Issue by cevich** [autotest/autotest-docker#612]
The `docker_daemon.start()` and `docker_daemon.restart_service` functions, along with the `daemon_options` configuration need to be reimplemented.  With the docker binary splitting into multiple parts, it no-longer makes sense to go after manipulating the daemon binary directly.  Instead, these functions should be backing-up, then modifying the `/etc/sysconfig/docker` file(s) and restarting the daemon using the `autotest.client.shared.service.SpecificServiceManager()` call.

**Comment by edsantiago** [comment]
This is a huge can of worms. Before you delve too deeply into it, can you check if the code is actually used? Last I looked at it, no code actually restarted the docker daemon.

**Comment by cevich** [comment]
> Last I looked at it, no code actually restarted the docker daemon.

I found the same, those subtests are long gone.  We had some tests that were flipping the selinux and ``icc`` flags.

Perhaps I should push this issue out to the next major version, where we don't need to be concerned with API breakage.  Yes it is a bit of a worm-can,  but the current function creates a bigger one, esp. for automated testing (like ADEPT) - discovery of the options used pre-docker-autotest is really fragile.  Much better to use the service manager (systemd) to do it ``properly`` than to try and bypass it.

**Comment by cevich** [comment]
Fixed by https://github.com/autotest/autotest-docker/pull/635
