### ISSUE TITLE
redhat/packaging test fails on Atomic Host

### ISSUE THREAD

**Issue by cevich** [autotest/autotest-docker#638]
```
	START	docker/subtests/redhat/packaging.56_1470299616	docker/subtests/redhat/packaging.56_1470299616	timestamp=1473802620	timeout=252	localtime=Sep 13 17:37:00	
		ERROR	docker/subtests/redhat/packaging.56_1470299616	docker/subtests/redhat/packaging.56_1470299616	timestamp=1473802622	localtime=Sep 13 17:37:02	Unhandled ImportError: No module named magic
  Traceback (most recent call last):
    File "/var/lib/autotest/client/parallel.py", line 26, in fork_start
      l()
    File "/var/lib/autotest/client/job.py", line 507, in <lambda>
      args, dargs))
    File "/var/lib/autotest/client/test.py", line 125, in runtest
      job.sysinfo.log_after_each_iteration)
    File "/var/lib/autotest/client/shared/test.py", line 893, in runtest
      exec ('import %s' % modulename, local_namespace, global_namespace)
    File "<string>", line 1, in <module>
    File "/var/lib/autotest/client/tests/docker/subtests/redhat/packaging/packaging.py", line 15, in <module>
      import magic
  ImportError: No module named magic
  
	END ERROR	docker/subtests/redhat/packaging.56_1470299616	docker/subtests/redhat/packaging.56_1470299616	timestamp=1473802622	localtime=Sep 13 17:37:02	
```

**Comment by cevich** [comment]
@edsantiago is there an easy way around using the ``magic`` module?  I didn't look closely, what is it used/needed for?

**Comment by edsantiago** [comment]
Sigh. I hate Atomic. I hate it so, so much.

No, there's no way around using libmagic other than completely rewriting the test.

**Comment by cevich** [comment]
Lol, it's beauty lies in it's utter simplicity....let's see...

**Comment by cevich** [comment]
I think there are two things needing fixing here:

    1.  ADEPT must make sure the python-magic package is installed
    2. The test should throw a TestNAError instead of an import error

Alternate idea:

``objdump`` **does** exist on atomic.  Could figure a way to ``utils.run()`` that and check.  IMHO, there is value to making sure debug symbols are in docker on atomic (we can't predict where it will need to be debugged).

Another idea: Have the test build a docker image that does the checking.

**Comment by cevich** [comment]
This will help also https://github.com/cevich/autotest-docker-enabled-product-testing/pull/56

**Comment by edsantiago** [comment]
/me hopes RHEL Atomic has the 'file' command. See pr 639. (Is there a way to attach a PR to this issue?)

**Comment by cevich** [comment]
Thanks Ed.

**Comment by edsantiago** [comment]
Thanks for reporting & testing!
